# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camera = QtWidgets.QPushButton(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(40, 40, 75, 23))
        self.camera.setObjectName("camera")
        self.video = QtWidgets.QPushButton(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(40, 70, 75, 23))
        self.video.setObjectName("video")
        self.figure = QtWidgets.QPushButton(self.centralwidget)
        self.figure.setGeometry(QtCore.QRect(40, 100, 75, 23))
        self.figure.setObjectName("figure")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 0, 640, 480))
        self.label.setText("")
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(40, 450, 75, 23))
        self.exit.setObjectName("exit")
        self.modess = QtWidgets.QComboBox(self.centralwidget)
        self.modess.setGeometry(QtCore.QRect(40, 140, 75, 23))
        self.modess.setEditable(False )
        self.modess.setObjectName("mode")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.camera.setText(_translate("MainWindow", "打开相机"))
        self.video.setText(_translate("MainWindow", "选择视频"))
        self.figure.setText(_translate("MainWindow", "选择图片"))
        self.exit.setText(_translate("MainWindow", "退出程序"))
        self.ComBoxaddItem()

    def ComBoxaddItem(self):
        '''
        向QComboBox控件中添加条目
        :return:
        '''
        self.modess.addItem('face_detc')
        self.modess.addItem('human_pose')
        self.modess.addItem('face_mesh')
        self.modess.addItem('hand_pose')
